# Generated by Django 6.0.2 on 2026-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
