# Generated by Django 6.0.2 on 2026-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0003_alter_deal_options_deal_created_by_deal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage for Salesman', max_digits=5),
        ),
    ]
