# Generated by Django 6.0.2 on 2026-02-26 17:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0006_userprofile_commission_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='deal',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['amount_paid'], name='LeadApp_dea_amount__7ef44d_idx'),
        ),
    ]
