# Generated by Django 6.0.2 on 2026-02-26 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0007_deal_amount_paid_alter_deal_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='LeadApp_dea_amount__7ef44d_idx',
        ),
        migrations.AddField(
            model_name='dealinstallment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='LeadApp.deal'),
        ),
        migrations.RemoveField(
            model_name='deal',
            name='amount_paid',
        ),
    ]
