# Generated by Django 6.0.2 on 2026-03-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0009_dealinstallment_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='commission_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='commission_percentage',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='salesman',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='deal',
        ),
        migrations.AddField(
            model_name='commission',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='LeadApp.dealinstallment'),
        ),
        migrations.AddField(
            model_name='commission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
