# Generated by Django 6.0.2 on 2026-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0011_commission_deleted_at_commission_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='verified',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverfied', max_length=20),
        ),
    ]
