# Generated by Django 6.0.2 on 2026-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0012_lead_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='verified',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverified', max_length=20),
        ),
    ]
