# Generated by Django 6.0.2 on 2026-03-09 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0015_alter_salestarget_options_salestarget_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='outgoing', max_length=10)),
                ('call_status', models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number'), ('voicemail', 'Voicemail')], max_length=20)),
                ('call_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='LeadApp.lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='LeadApp_cal_created_9b60d8_idx'), models.Index(fields=['call_status'], name='LeadApp_cal_call_st_58f4f9_idx')],
            },
        ),
    ]
