# Generated by Django 6.0.2 on 2026-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0017_calllog_updated_at_calllog_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('lead_source', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
