# Generated by Django 6.0.2 on 2026-03-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0019_remove_expense_date_expense_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expend_date',
            new_name='expense_date',
        ),
    ]
