# Generated by Django 6.0.2 on 2026-03-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0021_expense_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_deleted',
        ),
    ]
