# Generated by Django 6.0.2 on 2026-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadApp', '0022_remove_expense_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
